# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Horeca_node

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: ['18.x']
        
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test
        env:
          github_token: ${{ secrets.TOKEN }}
          PORT: ${{ secrets.PORT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER : ${{secrets.DB_USER}}
          DB_NAME : ${{secrets.DB_NAME}}
          SECRET_KEY : ${{secrets.SECRET_KEY}}
          EMAIL_USER: ${{secrets.EMAIL_USER}}
          EMAIL_PASS: ${{secrets.EMAIL_PASS}}
          PROJECT_LINK: ${{secrets.PROJECT_LINK}}
